trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/*
      - bicepconfig.json

pool:
  vmImage: 'ubuntu-latest'

variables:
  serviceConnection: '$(azureServiceConnection)'

stages:
  - template: templates/deploy-stage.yml
    parameters:
      environment: 'dev'
      paramFile: 'main.dev.bicepparam'
      serviceConnection: $(serviceConnection)

  - template: templates/deploy-stage.yml
    parameters:
      environment: 'acc'
      paramFile: 'main.acc.bicepparam'
      serviceConnection: $(serviceConnection)

  - template: templates/deploy-stage.yml
    parameters:
      environment: 'prod'
      paramFile: 'main.prod.bicepparam'
      serviceConnection: $(serviceConnection)
